/* Generated By:JJTree&JavaCC: Do not edit this line. TacParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TacParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int SUBT = 7;
  /** RegularExpression Id. */
  int MULT = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int LESSER = 10;
  /** RegularExpression Id. */
  int LESSEQUAL = 11;
  /** RegularExpression Id. */
  int GREATER = 12;
  /** RegularExpression Id. */
  int GREATEQUAL = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int LABEL = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int GOTO = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int VARIABLE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\":\"",
    "\"if\"",
    "\"goto\"",
    "<NUMBER>",
    "<VARIABLE>",
  };

}
