/* Generated By:JavaCC: Do not edit this line. TacParserTreeConstants.java Version 5.0 */
public interface TacParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTPOINT = 1;
  public int JJTIF = 2;
  public int JJTGOTO = 3;
  public int JJTCOMPARE = 4;
  public int JJTASSIGN = 5;
  public int JJTOPER = 6;
  public int JJTVOID = 7;
  public int JJTTERM = 8;
  public int JJTVARIABLE = 9;


  public String[] jjtNodeName = {
    "Expression",
    "Point",
    "If",
    "Goto",
    "Compare",
    "Assign",
    "Oper",
    "void",
    "Term",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=8af34b1ca5e2628dea31e72539d6c20f (do not edit this line) */
