/* Generated By:JavaCC: Do not edit this line. TacParserTreeConstants.java Version 5.0 */
public interface TacParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTASSIGN = 1;
  public int JJTOPER = 2;
  public int JJTVOID = 3;
  public int JJTTERM = 4;
  public int JJTVARIABLE = 5;


  public String[] jjtNodeName = {
    "Expression",
    "Assign",
    "Oper",
    "void",
    "Term",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=38bc413ca6909087227fa239def2c94e (do not edit this line) */
