/* Generated By:JavaCC: Do not edit this line. TacParserTreeConstants.java Version 5.0 */
public interface TacParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTLABEL = 1;
  public int JJTPOINT = 2;
  public int JJTIF = 3;
  public int JJTGOTO = 4;
  public int JJTCOMPARE = 5;
  public int JJTASSIGN = 6;
  public int JJTOPER = 7;
  public int JJTVOID = 8;
  public int JJTTERM = 9;
  public int JJTVARIABLE = 10;


  public String[] jjtNodeName = {
    "Expression",
    "Label",
    "Point",
    "If",
    "Goto",
    "Compare",
    "Assign",
    "Oper",
    "void",
    "Term",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=0ba55df960256f1ec41893722355eab7 (do not edit this line) */
